Repository 42Statistics/42Stat-Frontend, pull requests merged in 2023-08, with the labels that each got.

#216 🐛 [BugFix] LandingLayout 공통으로 Center 추가
  app/src/@core/layouts/LandingLayout/index.tsx
  app/src/FtOAuthRedirect/index.tsx
  app/src/Landing/index.tsx
Labels: bug

#218 ✨ [Feature] 리더보드 집계기간
  app/src/Leaderboard/components/Leaderboard/index.tsx
  app/src/Leaderboard/tabs/CoalitionScore/LeaderboardCoalitionScoreTabResult.tsx
  app/src/Leaderboard/tabs/EvalCount/LeaderboardEvalCountTabResult.tsx
  app/src/Leaderboard/tabs/ExpIncrement/LeaderboardExpIncrementTabResult.tsx
  app/src/Leaderboard/tabs/Level/LeaderboardLevelTabResult.tsx
  app/src/Leaderboard/tabs/Level/index.tsx
Labels: enhancement

#220 🐛 fix: 401 interceptor 를 ApolloClient contructor 에 직접 전달하도록 변경
  app/src/@core/providers/ApolloProvider.tsx
Labels: bug

#221 🐛 fix: EvalLogSearchTitle 의 totalCount 가 query 의 error 나 loading 상태를 반영하도록 수정
  app/src/EvalLogSearch/index.tsx
Labels: bug

#226 🐛 fix: LogtimRecord login 인자 추가
  app/src/@shared/__generated__/gql.ts
  app/src/@shared/__generated__/graphql.ts
  app/src/Profile/dashboard-contents/General/LogtimeRecord.tsx
Labels: bug

#233 ♻️ refactor: hoc 패턴 삭제
  app/index.html
  app/src/@core/components/Footer/index.tsx
  app/src/@shared/components/Seo.tsx
  app/src/@shared/hoc/withFooter.tsx
  app/src/@shared/hoc/withHead.tsx
  app/src/Error/404.tsx
  app/src/EvalLogSearch/index.tsx
  app/src/FtOAuth/index.tsx
  app/src/Home/index.tsx
  app/src/Landing/index.tsx
  app/src/Leaderboard/pages/CoalitionScore/index.tsx
  app/src/Leaderboard/pages/EvalCount/index.tsx
  app/src/Leaderboard/pages/ExpIncrement/index.tsx
  app/src/Leaderboard/pages/Level/index.tsx
  app/src/Profile/pages/Eval/index.tsx
  app/src/Profile/pages/General/index.tsx
  app/src/Profile/pages/Versus/index.tsx
  app/src/Project/ProjectDetailPage.tsx
  app/src/Setting/index.tsx
  app/src/Team/index.tsx
Labels: enhancement

#234 💄 design: LinkSection Mobile
  app/src/Setting/sections/LinkGoogleSection/LinkLabel.tsx
  app/src/Setting/sections/LinkGoogleSection/LinkRow.tsx
  app/src/Setting/sections/LinkGoogleSection/index.tsx
Labels: bug

#235 🐛 fix: Safari 레벨 증가 그래프 undefined
  app/src/Profile/dashboard-contents/General/LevelRecords.tsx
  app/src/Profile/dashboard-contents/Versus/LevelRecords.tsx
Labels: bug

#241 :recycle: refactor: eval log search 페이지 리팩토링
  app/src/@core/providers/ApolloProvider.tsx
  app/src/@shared/__generated__/gql.ts
  app/src/@shared/__generated__/graphql.ts
  app/src/@shared/components/EvalLogList/EvalLogList.tsx
  app/src/@shared/components/EvalLogList/EvalLogListItem.tsx
  app/src/@shared/hooks/useInfiniteScroll.ts
  app/src/@shared/hooks/useIntersection.ts
  app/src/@shared/types/EvalLogSearchModel.d.ts
  app/src/EvalLogSearch/api/getEvalLogs.ts
  app/src/EvalLogSearch/atoms/evalLogSearchArgsAtom.ts
  app/src/EvalLogSearch/atoms/evalLogSearchTotalCountAtom.ts
  app/src/EvalLogSearch/components/EvalLogSearchAbsoluteButton.tsx
  app/src/EvalLogSearch/components/EvalLogSearchArgsDialogTrigger.tsx
  app/src/EvalLogSearch/components/EvalLogSearchContent.tsx
  app/src/EvalLogSearch/components/EvalLogSearchDialog.tsx
  app/src/EvalLogSearch/components/EvalLogSearchHeader.tsx
  app/src/EvalLogSearch/components/EvalLogSearchResult.tsx
  app/src/EvalLogSearch/components/EvalLogSearchSeo.tsx
  app/src/EvalLogSearch/components/EvalLogSearchTitle.tsx
  app/src/EvalLogSearch/components/EvalLogSearchURLReader.tsx
  app/src/EvalLogSearch/constants/evalLogArgsText.ts
  app/src/EvalLogSearch/constants/resultPerPage.ts
  app/src/EvalLogSearch/constants/urlParams.ts
  app/src/EvalLogSearch/hooks/useInfiniteScrollIndex.ts
  app/src/EvalLogSearch/hooks/useSearchTotalCount.ts
  app/src/EvalLogSearch/index.tsx
Labels: bug, enhancement

#253 ✨ feat: 서비스 피드백
  app/src/Setting/constants/feedbackUrl.ts
  app/src/Setting/index.tsx
  app/src/Setting/sections/FeedbackSection/index.tsx
Labels: enhancement

#254 🐛 fix: Layout 밖으로 Link를 뺐을 때 :focus가 적용되지 않음
  app/src/@core/components/NavBar/Desktop/DesktopNavItem.tsx
  app/src/@core/components/NavBar/Tablet/TabletNavItem.tsx
  app/src/@shared/ui-kit/Tab/Tab.tsx
  app/src/Leaderboard/components/Leaderboard/LeaderboardListItem.tsx
Labels: bug

#255 🚧 fix: 400 Interceptor 조건 분기
  app/src/@core/providers/ApolloProvider.tsx
Labels: bug

#256 🐛 fix: /auth/ft/request로 직접 접근할 수 있는 버그
  app/src/FtOAuthRequest/index.tsx
Labels: bug

#259 :bug: fix: GET_RECENT_TEAM_RESULT query 에 불필요한 인자를 제공하던 문제 수정
  app/src/Home/dashboard-contents/Team/RecentExamResult.tsx
Labels: bug

#260 🔍 chore: google analytics tag
  app/index.html
Labels: enhancement

#263 🐛 fix: TeamUserPreview id 캐싱 문제로 non-normalized
  app/src/@shared/__generated__/gql.ts
  app/src/@shared/__generated__/graphql.ts
  app/src/@shared/types/fragments/TEAM_USER_PREVIEW_FIELDS.ts
  app/src/Team/index.tsx
Labels: bug

#267 fix: :bug: useAuth 에서 getMyInfo 사용하도록 수정, MyInfo 가 nullable 한 상황 대응
  app/src/@core/guards/hooks/useAuth.ts
  app/src/@shared/__generated__/gql.ts
  app/src/@shared/__generated__/graphql.ts
  app/src/@shared/atoms/userAtom.ts
  app/src/Home/components/Hero/index.tsx
  app/src/Home/components/MyInfo/api/getInidividualizedMessage.ts
  app/src/Home/components/MyInfo/hooks/useIndividualizedMessage.tsx
  app/src/Home/components/MyInfo/index.tsx
  app/src/Home/index.tsx
Labels: bug

#276 fix(design): 팀 페이지 평가기록 짧을 때도 채워지도록 수정
  app/src/Team/index.tsx
Labels: bug

#277 fix(EvalLogSearchContent): missing footer
  app/src/EvalLogSearch/components/EvalLogSearchContent.tsx
Labels: bug

#282 feat(PreferredTime): 200시간 이상 출석왕
  app/src/Profile/dashboard-contents/General/PreferredTime.tsx
Labels: enhancement

#287 fix(Chart): 레벨 증가 그래프 모든 legend 껐을 때 x축 수치 달라짐
  app/src/Profile/dashboard-contents/General/LevelRecords.tsx
  app/src/Profile/dashboard-contents/Versus/LevelRecords.tsx
Labels: bug
